(function(){
'use strict';
var members=[
{
name:'Jason',initials:'J',photo:'/assets/profile/Jason.jpg',role:{zh:'創辦人暨 CEO',en:'Founder & CEO'},skills:{zh:['永續溝通','專案管理','領導力'],en:['Sustainability','Project management','Leadership']},intro:{zh:'哈囉，我是 Jason 簡嘉信！我一直希望能讓永續這件事變得更平易近人，平時我和朋友組隊推廣永續議題，也在網路上分享各種永續新知。我熱衷於將複雜難懂的議題，轉譯成大家日常都能輕鬆吸收的內容。期待能透過最簡單直接的分享，陪大家一起把這些理念落實在生活裡，讓永續成為一件自然而然的事。',en:'Hi, I’m Jason Chien. I want sustainability to feel practical, friendly, and easy to bring into everyday life. I work with friends to share sustainability topics and turn complex ideas into useful stories people can understand at a glance. My goal is to help more people make better choices naturally—one clear, doable step at a time.'},experience:{zh:['115年1月／個人發起「永續資訊道相報」LINE 社群，推廣永續資訊與新知。','114年10月／參與臺北農業淨零工作坊，完成農業部門碳盤查訓練課程。','114年9月2日／代表 FishFull 漁有料參加 2025 臺灣國際海洋青年論壇，榮獲青年組創新視界獎。','114年8月／代表「回山海・青行動」參加新北 2025 國際青年氣候行動論壇，榮獲佳作。','113年10月／代表環保星勢力國際服務志工隊，赴南韓參與第 27 屆 IAVE 國際志工大會。'],en:['Jan 2026 — Founded the “Sustainability News Sharing” LINE community to make sustainability updates easier to follow.','Oct 2025 — Completed agricultural carbon-accounting training at the Taipei Agriculture Net-Zero Workshop.','Sep 2, 2025 — Represented FishFull at the Taiwan International Ocean Youth Forum and received the Youth Innovation Vision Award.','Aug 2025 — Represented the Back to Mountains and Sea Youth Action team at the New Taipei International Youth Climate Action Forum and received an Honorable Mention.','Oct 2024 — Joined the 27th IAVE World Volunteer Conference in South Korea with the Environmental Rising Stars international volunteer team.']}
},
{
name:'橘子',initials:'橘',photo:'/assets/profile/橘子.png',role:{zh:'PM',en:'Project Manager'},skills:{zh:['教學設計','專案規劃','永續教育'],en:['Teaching','Project planning','Sustainability']},intro:{zh:'大家好！我是橘子（本名王翊軒），現在就讀清大教育學院學士班大四。因為本人是橘色痴迷狂，很多東西都是橘色，故稱橘子 XD。自小便對環境保育充滿熱忱，高中與大學期間累積了許多志工活動、永續專案及研究計畫經驗，包含碳匯主題課程設計與河川教育 LINE Chatbot 開發。很高興在這個團隊與各位夥伴相聚！',en:'Hi! I’m Orange, also known as Wang Yi-Hsuan, a senior in the Interdisciplinary Program of Education at National Tsing Hua University. I’m famously obsessed with orange, so the nickname stuck XD. My passion for environmental conservation started early and grew through volunteer work, sustainability projects, and research. My projects include carbon-sequestration curriculum design and a river-education LINE chatbot. I’m excited to build meaningful learning experiences with the FishFull crew.'},experience:{zh:['115年1月10日／參與聯合報「河好如初」設計思考工作坊決選，團體成果發表榮獲第一名及五萬元獎金。','114年11月12日／第十屆「聯電綠獎」榮獲青年行動獎佳作，獎金一萬五千元。','114年9月2日／參加 2025 臺灣國際海洋青年論壇，榮獲青年組創新視界獎。','114年2月／國科會大學生專題研究計畫獲核定，題目為「碳匯課程設計：探討小學生學習過程中的態度與能力」，執行經費 48,000 元。','113年8月／2024 新北氣候行動團隊創意徵件，榮獲銀獎（提案創意獎，全國第二）。'],en:['Jan 10, 2026 — Won first place and NT$50,000 at the United Daily News “River, Better Again” design-thinking workshop final showcase.','Nov 12, 2025 — Received an Honorable Mention in the Youth Action category at the 10th UMC Green Award, with a NT$15,000 prize.','Sep 2, 2025 — Received the Youth Innovation Vision Award at the 2025 Taiwan International Ocean Youth Forum.','Feb 2025 — Awarded a National Science and Technology Council undergraduate research grant of NT$48,000 for a carbon-sequestration curriculum study focused on elementary students’ attitudes and abilities.','Aug 2024 — Won Silver, ranking second nationwide, in the 2024 New Taipei Climate Action Team idea competition.']}
},
{
name:'盧姸諠',initials:'姸',photo:'/assets/profile/盧姸諠.jpeg',role:{zh:'行銷部部長',en:'Head of Marketing'},skills:{zh:['領導力','專案管理','教學與轉譯'],en:['Leadership','Project management','Teaching']},intro:{zh:'哈囉大家，我是姸諠。我最喜歡觀察＋思考，常常有好點子，不過行動力比較差，正在努力克服……經歷上，我在設計思考數據分析社團中擔任行銷，目前接任社長，也完成兩項數據分析與顧問的企業專案，寒假短期在環資基金會實習。稍微擅長社群圖文發想、基礎數據整理與分析，以及統整資料。希望把比較平淡、沒人注意的小事，透過各種方式變得有趣又吸睛！',en:'Hi, I’m Yen-Hsuan. I love observing, questioning, and turning small details into fresh ideas. I have led marketing for a design-thinking and data-analysis club and now serve as its president. I have also completed two corporate data and consulting projects and interned with the Environmental Rights Foundation. I enjoy social content, practical data analysis, and making overlooked stories feel relevant, interesting, and worth sharing.'},experience:{zh:['環境教育方法實作。','環境與資源相關實習：循環經濟推廣專案、活動策劃與關係人聯繫。'],en:['Hands-on environmental education methods.','Environmental and resource-sector internship covering circular-economy outreach, event planning, and stakeholder coordination.']}
},
{
name:'龔依吟',initials:'吟',photo:'/assets/profile/龔依吟.png',role:{zh:'行銷部成員',en:'Marketing Team'},skills:{zh:['活動企劃','跨部門溝通','外部協調'],en:['Event planning','Cross-team communication','External coordination']},intro:{zh:'我是龔依吟，也可以叫我洗衣精，在漁有料團隊裡負責行銷文案製作。我結合數位工具整合與跨領域轉譯專長，致力於推動永續發展。曾獲中鼎永續生活實驗提案入選及茶產業創業工作坊銀獎，擅長將複雜的論文與產地數據結構化，轉化為直覺的食魚教育內容。我深信「唯有兼顧商業可行性，永續才能落地」，期盼以高效執行力為永續漁業創造實質影響力。',en:'I’m Yi-Yin Kung, and you can call me Laundry Detergent. I create marketing copy for FishFull and combine digital tools with cross-disciplinary storytelling to move sustainability from ideas into action. I enjoy organizing research papers and origin data into seafood education that feels clear and intuitive. I believe sustainability works best when it also makes business sense, and I aim to turn that belief into measurable impact for responsible fisheries.'},experience:{zh:['2026年2月／參與中興大學「興心茶語」永續茶產業工作坊。','2026年3月／中鼎永續生活實驗室入選團隊。','永續茶產業工作坊銀獎團隊。'],en:['Feb 2026 — Joined National Chung Hsing University’s “Sustainable Tea Industry” workshop.','Mar 2026 — Selected for the CTCI Sustainable Living Lab.','Member of a Silver Award team in a sustainable tea-industry entrepreneurship workshop.']}
},
{
name:'劉道宗',initials:'宗',photo:'/assets/profile/劉道宗.jpg',role:{zh:'行銷部美工',en:'Visual Designer'},skills:{zh:['視覺設計','專案規劃'],en:['Design','Project planning']},intro:{zh:'我叫劉道宗，也可以叫我阿宗，是科普漫畫家兼設計師，在漁有料團隊中擔任行銷組美工設計。平常除了關注各類議題，也會盡可能參與活動、多認識人並增進新知。',en:'I’m Tao-Tsung Liu, or A-Tsung. I’m a science comic artist and designer, and I create visual work for FishFull’s marketing team. I follow a wide range of topics, join events whenever I can, meet new people, and keep learning so our seafood stories can stay fresh, accurate, and visually engaging.'},experience:{zh:['文策院 ESG 辦公室永續活動 Pitch，連續兩年獲選提報。'],en:['Selected to present sustainability event pitches through the Taiwan Creative Content Agency ESG Office for two consecutive years.']}
},
{
name:'蔡福洋',initials:'洋',photo:'/assets/profile/蔡福洋.jpg',role:{zh:'AR／VR 技術負責人',en:'AR/VR Lead'},skills:{zh:['系統整合','領導力','目標導向'],en:['Integration','Leadership','Goal-oriented']},intro:{zh:'大家好！我是蔡福洋，在漁有料團隊裡擔任 AR／VR 技術負責人。過去的跨領域背景，讓我從不把自己侷限在典型框架裡。我熱衷跨領域學習並具備彈性，期許自己能靈活適應團隊中的各種場合與任務挑戰。喜歡嘗試新鮮事物，過去在永續、科技創新、外交、志工服務等領域都有涉獵。期待未來發揮技術專長，也帶著開放的心態和大家合作，一起激盪更多創新火花！',en:'Hi! I’m Fu-Yang Tsai, FishFull’s AR/VR lead. My cross-disciplinary background keeps me from staying inside one box. I enjoy learning across fields, adapting to new challenges, and testing ideas that connect sustainability, technology, international exchange, and volunteer service. I’m excited to use immersive technology with an open, collaborative mindset and help the team create seafood experiences people can truly feel and remember.'},experience:{zh:['2022 VR × SDGs 全國跨域盃虛擬實境大賽，決賽佳作。','2023 基隆市海洋保育魚苗放流活動，擔任團隊代表。','2024 第64屆高級中等學校北區科展工程學科，「海上搜救識別系統」榮獲特優。','2026 AIESEC 國際經濟商管學生會會長。'],en:['2022 — Honorable Mention finalist in the national VR × SDGs Cross-Disciplinary Cup.','2023 — Team representative at a Keelung marine-conservation fish-release event.','2024 — Top Award in Engineering at the 64th Northern Taiwan High School Science Fair for a maritime search-and-rescue identification system.','2026 — President of AIESEC, the international association of students in economics and business.']}
},
{
name:'阿薛',initials:'薛',photo:'/assets/profile/阿薛.jpg',role:{zh:'IT',en:'IT'},skills:{zh:['軟體工程','地圖應用','教學轉譯'],en:['Software engineering','Maps','Teaching']},intro:{zh:'我是 FishFull 的 IT，負責把永續漁產、友善海鮮地圖與數位體驗串起來。I build tech that helps people find better seafood, support local fishers, and understand sustainability in a simple way. 希望用科技讓海鮮選擇更透明、更年輕、更有感。',en:'I’m FishFull’s IT lead. I connect responsible seafood, friendly seafood maps, and digital experiences. I build tech that helps people find better seafood, support local fishers, and understand sustainability in a simple way. My goal is to make seafood choices more transparent, more approachable for younger audiences, and more connected to real life.'},experience:{zh:['台大氣候行動社小編。','TWYCC 行銷部小編。','奉茶計畫總統黑客松成員。'],en:['Social media editor for the NTU Climate Action Club.','Marketing team social media editor at TWYCC.','Member of the Feng Cha Project team in the Presidential Hackathon.']}
},
{
name:'黃冠豪',initials:'豪',photo:'/assets/profile/黃冠豪.jpeg',role:{zh:'團隊夥伴（職位未定）',en:'Team Member (Role to be confirmed)'},skills:{zh:['教學','永續倡議','外部協調'],en:['Teaching','Sustainability','External coordination']},intro:{zh:'宜智科技 CFO，台大財金畢業，四次書卷獎、一次校長獎，並獲教育部總統教育獎奮發向上獎。大學期間建立 SDGs 社團，也在多項競賽中獲得冠亞軍。',en:'CFO of Yi-Zhi Technology and a graduate of National Taiwan University’s Department of Finance. He received four Academic Achievement Awards, one President’s Award, and the Ministry of Education’s Presidential Education Award for perseverance. During university, he founded an SDGs club and earned top placements in multiple competitions.'},experience:{zh:['在台大創立 SDGs 社團。','在立法院與各國夥伴簽署永續 MOU。','多個永續競賽冠軍與亞軍。'],en:['Founded an SDGs club at National Taiwan University.','Signed sustainability MOUs with international partners at the Legislative Yuan.','Won first- and second-place honors in multiple sustainability competitions.']}
}
];
var copy={
zh:{title:'關於我們',meta:'FishFull 漁有料｜關於我們',desc:'認識 FishFull 漁有料團隊：把永續漁產、食魚教育、友善海鮮地圖與 AR 體驗做得更好懂、更好用。',eyebrow:'MEET THE CREW',headline:'一群把好魚故事，做得更好懂的人',lead:'我們來自永續、教育、設計、行銷、專案管理與科技。共同目標很簡單：讓消費者更敢買魚、魚販更好介紹、漁業夥伴的努力更容易被看見。',chips:['永續不是硬課本','把產地故事說清楚','讓年輕人也想逛魚攤','科技要真的幫得上忙'],artTitle:'從海上到手機，再回到餐桌',artText:'把漁獲來源、選魚知識、買魚地圖與沉浸體驗接成一條順手路線。',teamEyebrow:'OUR TEAM',teamTitle:'認識漁有料夥伴',teamText:'每個人專長不同，但都在做同一件事：讓友善海鮮不只被看見，也能被理解、被選擇、被帶回家。',expTitle:'永續相關經歷',promiseEyebrow:'WHAT WE CARE ABOUT',promiseTitle:'我們在意的三件事',promises:[['資訊要看得懂','不用背艱深名詞，也能知道魚從哪來、怎麼挑、怎麼煮。'],['工具要用得上','不只談理念，還要讓地圖、AR、食譜與現場介紹真的派上用場。'],['好魚要被支持','讓消費者的每次選擇，都更有機會回到在地漁業與海洋。']],footer:'Copyright © 2026 FishFull 漁有料 版權所有'},
en:{title:'About Us',meta:'FishFull | About Us',desc:'Meet the FishFull team making responsible seafood, seafood education, maps, and AR easier to understand and use.',eyebrow:'MEET THE CREW',headline:'We make good seafood stories easier to understand',lead:'Our team brings together sustainability, education, design, marketing, project management, and technology. Our shared goal is simple: help shoppers buy seafood with confidence, help fishmongers tell a clearer story, and help the work behind responsible fishing get noticed.',chips:['No textbook talk','Clear stories from sea to stall','Seafood culture for a new generation','Tech that earns its place'],artTitle:'From the sea to your phone—and back to the table',artText:'We connect catch stories, seafood know-how, places to buy, and immersive tools into one easy route.',teamEyebrow:'OUR TEAM',teamTitle:'Meet the FishFull crew',teamText:'Different skills, one mission: help responsible seafood get seen, understood, chosen, and enjoyed at the table.',expTitle:'Sustainability experience',promiseEyebrow:'WHAT WE CARE ABOUT',promiseTitle:'Three things guide our work',promises:[['Keep it clear','People should understand where seafood comes from, how to choose it, and how to cook it—without a glossary.'],['Make it useful','Maps, AR, recipes, and counter-side stories should help people take the next step, not just sound impressive.'],['Back better seafood','Every informed choice can send more support toward local fishing communities and a healthier ocean.']],footer:'Copyright © 2026 FishFull. All rights reserved.'}
};
function isEn(){return localStorage.getItem('scm-language')==='en'}
function esc(v){return String(v).replace(/[&<>'"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]})}
function nav(lang){var items=lang==='en'?[['Home','/'],['Fish AR','/ar'],['Featured Fish','/pages/fish.html'],['Buy Nearby','/pages/map.html'],['Easy Recipes','/pages/recipes.html']]:[['首頁','/'],['AR 看真魚','/ar'],['主推魚','/pages/fish.html'],['去附近買魚','/pages/map.html'],['零失敗食譜','/pages/recipes.html']];return items.map(function(x){return '<a href="'+x[1]+'">'+esc(x[0])+'</a>'}).join('')}
function memberCard(m,lang,t){var skills=m.skills[lang].map(function(s){return '<span>'+esc(s)+'</span>'}).join('');var exp=m.experience[lang].map(function(x){return '<li>'+esc(x)+'</li>'}).join('');return '<article class="member-card"><div class="portrait-wrap"><img class="portrait" src="'+esc(m.photo)+'" alt="'+esc(m.name)+'" loading="lazy" decoding="async"><span class="portrait-fallback" aria-hidden="true">'+esc(m.initials)+'</span></div><div><span class="role">'+esc(m.role[lang])+'</span><h3>'+esc(m.name)+'</h3><div class="skills">'+skills+'</div></div><p class="intro">'+esc(m.intro[lang])+'</p><div class="experience"><h4>'+esc(t.expTitle)+'</h4><ol>'+exp+'</ol></div></article>'}
function render(){var lang=isEn()?'en':'zh',t=copy[lang],root=document.getElementById('root');document.documentElement.classList.toggle('lang-en',lang==='en');document.documentElement.lang=lang==='en'?'en':'zh-Hant';document.title=t.meta;var meta=document.querySelector('meta[name=description]');if(meta)meta.content=t.desc;root.innerHTML='<div class="page"><header class="topbar"><a class="brand" href="/"><img src="/fishfull.jpg" alt="FishFull 漁有料"><span class="brand-copy"><strong>FISHFULL Green Seafood</strong><span>漁有料</span></span></a><nav class="nav" aria-label="Main navigation">'+nav(lang)+'</nav><div class="actions"><a class="icon-btn" href="/" aria-label="Home">⌂</a><button class="icon-btn" id="lang-toggle" type="button" aria-label="Language">'+(lang==='en'?'中':'EN')+'</button></div></header><main><section class="hero"><div class="hero-copy"><p class="eyebrow">'+esc(t.eyebrow)+'</p><h1>'+esc(t.headline)+'</h1><p class="hero-lead">'+esc(t.lead)+'</p><div class="hero-chips">'+t.chips.map(function(x){return '<span>'+esc(x)+'</span>'}).join('')+'</div></div><div class="hero-art" aria-label="Ocean illustration"><span class="sun"></span><span class="wave"></span><span class="fish-shape"></span><i class="seaweed one"></i><i class="seaweed two"></i><i class="seaweed three"></i><i class="seaweed four"></i><div class="art-copy"><strong>'+esc(t.artTitle)+'</strong><span>'+esc(t.artText)+'</span></div></div></section><section class="team-section"><div class="section-head"><p class="eyebrow">'+esc(t.teamEyebrow)+'</p><h2>'+esc(t.teamTitle)+'</h2><p>'+esc(t.teamText)+'</p></div><div class="team-grid">'+members.map(function(m){return memberCard(m,lang,t)}).join('')+'</div></section><section class="promise-section"><div class="section-head"><p class="eyebrow">'+esc(t.promiseEyebrow)+'</p><h2>'+esc(t.promiseTitle)+'</h2></div><div class="promise-grid">'+t.promises.map(function(p){return '<article class="promise"><b>'+esc(p[0])+'</b><p>'+esc(p[1])+'</p></article>'}).join('')+'</div></section></main><footer class="footer"><strong>FishFull 漁有料</strong><span>'+esc(t.footer)+'</span></footer></div>';document.querySelectorAll('.portrait').forEach(function(img){function fallback(){img.parentElement.classList.add('is-fallback')}img.addEventListener('error',fallback,{once:true});if(img.complete&&img.naturalWidth===0)fallback()});document.getElementById('lang-toggle').addEventListener('click',function(){localStorage.setItem('scm-language',lang==='en'?'zh':'en');render()})}
document.addEventListener('DOMContentLoaded',render);
})();